chore: Coderabbit INSTALL_ALL  validation

diff --git a/Dockerfile.tools b/Dockerfile.tools
--- a/Dockerfile.tools
+++ b/Dockerfile.tools
@@ -53,7 +53,7 @@ ARG TRIVY_VERSION=${TRIVY_VERSION:-false}
 # In RUN command below used `. /.env` <- this is sourcing vars that
 # specified in step below
 ARG INSTALL_ALL=${INSTALL_ALL:-false}
-RUN if [ "$INSTALL_ALL" != "false" ]; then \
+RUN if [ "$INSTALL_ALL" = "true" ] || [ "$INSTALL_ALL" - "latest" ]; then \
         echo "OPENTOFU_VERSION=latest"       >> /.env && \
         echo "TERRAFORM_VERSION=latest"      >> /.env && \
         \
@@ -67,6 +67,8 @@ RUN if [ "$INSTALL_ALL" != "false" ]; then \
         echo "TFSEC_VERSION=latest"          >> /.env && \
         echo "TFUPDATE_VERSION=latest"       >> /.env && \
         echo "TRIVY_VERSION=latest"          >> /.env \
+    elif [ "$INSTALL_ALL" != "false"]; then \
+        echo "ERROR: INSTALL_ALL must be 'true', 'latest', or 'false'" >&2 && exit 1; \
     ; fi
 
 # Docker `RUN`s shouldn't be consolidated here
